"""data

Revision ID: 6ce2d685e3f6
Revises: c9f3ac79a021
Create Date: 2023-11-04 23:20:36.167656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ce2d685e3f6'
down_revision = 'c9f3ac79a021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('sort', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_api_id'), ['api_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_api_id'))

    op.drop_table('data')
    # ### end Alembic commands ###
