"""api.name unique

Revision ID: 43c4a68781f0
Revises: 6ce2d685e3f6
Create Date: 2023-11-05 02:07:29.052945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c4a68781f0'
down_revision = '6ce2d685e3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apis_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apis_name'))

    # ### end Alembic commands ###
