"""apis

Revision ID: c9f3ac79a021
Revises: cc1059b24b1e
Create Date: 2023-11-04 22:16:18.556568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f3ac79a021'
down_revision = 'cc1059b24b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apis_user_id'), ['user_id'], unique=False)

    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('sort', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('bool', 'number', 'string', name='field_type'), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('content_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fields_api_id'), ['api_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fields_api_id'))

    op.drop_table('fields')
    with op.batch_alter_table('apis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apis_user_id'))

    op.drop_table('apis')

    op.execute('DROP TYPE field_type')
    # ### end Alembic commands ###
